"""Exercise the REAL Claude vision path end-to-end and write docs/VISION_DEMO.md.

Unlike `run_eval.py` (deterministic, offline, injected content), this script
uploads actual document IMAGES to `POST /claims/upload`, so Claude vision really
classifies and extracts them. It needs `ANTHROPIC_API_KEY` set and makes live API
calls (a handful of vision requests).

    .venv/bin/python scripts/make_sample_docs.py   # generate the images first
    .venv/bin/python scripts/run_vision_demo.py    # then run the live demo
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

os.environ["USE_LLM"] = "true"  # force the live vision path
ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from fastapi.testclient import TestClient  # noqa: E402

from app.config import get_settings  # noqa: E402
from app.main import create_app  # noqa: E402

SAMPLES = ROOT / "samples"

# Each scenario: a human title, the form fields, and the files to upload.
SCENARIOS = [
    {
        "title": "Clean approval — prescription + hospital bill (real images)",
        "note": "Both images are classified and extracted by Claude vision, then "
        "adjudicated deterministically. Expect APPROVED ~1350 (10% co-pay).",
        "form": {
            "member_id": "EMP001",
            "policy_id": "PLUM_GHI_2024",
            "claim_category": "CONSULTATION",
            "treatment_date": "2024-11-01",
            "claimed_amount": "1500",
        },
        "files": ["prescription_rajesh.png", "hospital_bill_rajesh.png"],
    },
    {
        "title": "Wrong document — pharmacy bill where a hospital bill is required",
        "note": "A CONSULTATION needs PRESCRIPTION + HOSPITAL_BILL. Claude classifies "
        "the second image as a PHARMACY_BILL, so the gate stops the claim before any "
        "decision with a specific message.",
        "form": {
            "member_id": "EMP001",
            "policy_id": "PLUM_GHI_2024",
            "claim_category": "CONSULTATION",
            "treatment_date": "2024-11-01",
            "claimed_amount": "1500",
        },
        "files": ["prescription_rajesh.png", "pharmacy_bill_clear.png"],
    },
    {
        "title": "Unreadable document — blurry phone photo of a pharmacy bill",
        "note": "Claude judges the blurry image unreadable, so the gate asks the "
        "member to re-upload that specific document (the claim is paused, not rejected).",
        "form": {
            "member_id": "EMP004",
            "policy_id": "PLUM_GHI_2024",
            "claim_category": "PHARMACY",
            "treatment_date": "2024-10-25",
            "claimed_amount": "253",
        },
        "files": ["prescription_rajesh.png", "pharmacy_bill_blurry.png"],
    },
]


def _multipart(files: list[str]) -> list[tuple[str, tuple[str, bytes, str]]]:
    out = []
    for name in files:
        out.append(("files", (name, (SAMPLES / name).read_bytes(), "image/png")))
    return out


def _trace_lines(trace: list[dict]) -> list[str]:
    lines = []
    for t in trace:
        lines.append(f"- `{t['step']}` **{t['status']}** — {t['detail']}")
    return lines


def _render(scenario: dict, body: dict) -> list[str]:
    out = [f"## {scenario['title']}", "", f"_{scenario['note']}_", ""]
    out.append(f"**Uploaded:** {', '.join(scenario['files'])}  ")
    out.append(f"**Category:** {scenario['form']['claim_category']}, "
               f"claimed ₹{scenario['form']['claimed_amount']}")
    out.append("")
    out.append(f"**Status:** `{body.get('status')}`  ")
    if body.get("decision"):
        out.append(f"**Decision:** `{body['decision']}`  ")
    if body.get("approved_amount") is not None:
        out.append(f"**Approved amount:** ₹{body['approved_amount']}  ")
    if body.get("confidence") is not None:
        out.append(f"**Confidence:** {body['confidence']}  ")
    if body.get("degraded"):
        out.append("**Degraded:** true  ")
    out.append("")
    for issue in body.get("blocking_issues", []):
        out.append(f"> ⛔ **{issue['reason']}** — {issue['message']}")
        out.append("")
    if body.get("explanation"):
        out.append(f"**Explanation:** {body['explanation']}")
        out.append("")
    out.append("**Trace (live vision path):**")
    out.append("")
    out.extend(_trace_lines(body.get("trace", [])))
    out.append("")
    out.append("---")
    out.append("")
    return out


def main() -> None:
    get_settings.cache_clear()
    settings = get_settings()
    app = create_app()

    report: list[str] = [
        "# Vision Demo — the REAL Claude vision path",
        "",
        "Generated by `scripts/run_vision_demo.py`. Unlike the deterministic eval "
        "(`docs/EVAL_REPORT.md`, injected content, offline), this uploads actual "
        "document **images** to `POST /claims/upload`, so Claude vision classifies "
        "and extracts them for real, then the deterministic rule engine decides.",
        "",
        f"Model: `{settings.llm_model}`.",
        "",
        "---",
        "",
    ]

    with TestClient(app) as client:
        if getattr(app.state, "llm", None) is None:
            report.append(
                "> **LLM not configured** (no `ANTHROPIC_API_KEY` / `USE_LLM=false`). "
                "Set the key and re-run to capture the live vision output."
            )
            (ROOT / "docs" / "VISION_DEMO.md").write_text("\n".join(report), encoding="utf-8")
            print("LLM not configured; wrote a stub VISION_DEMO.md.")
            return

        for scenario in SCENARIOS:
            print(f"Running: {scenario['title']}")
            try:
                resp = client.post(
                    "/claims/upload",
                    data=scenario["form"],
                    files=_multipart(scenario["files"]),
                )
                body = resp.json()
            except Exception as exc:  # noqa: BLE001 - capture, keep going
                report.append(f"## {scenario['title']}\n\n> Demo error: {exc}\n\n---\n")
                continue
            report.extend(_render(scenario, body))

    out_path = ROOT / "docs" / "VISION_DEMO.md"
    out_path.write_text("\n".join(report), encoding="utf-8")
    print(f"Wrote {out_path}")


if __name__ == "__main__":
    main()
